# try:
#     print(a)
# except BaseException:
#     print("TEST")
import random

# try:
#     print(a)
# except Exception as msg:
#     print(msg)
# else:
#     print('没有异常才会执行我，最后的代码')
# finally:
#     print('有无异常都会执行我')


#raise可以抛出异常

# num =random.randint(1,4)
# if num % 2 ==0:
#     raise Exception(f'{num}是偶数')
# else:
#     raise NameError(f'{num}是奇数')